spring:
  application:
    name: app1
  config:
    import: 'optional:configserver:'
  profiles:
    active: default
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
management:
  endpoints:
    web:
      exposure:
        include: refresh,env,health,info


grpc:
  client:
    EventEmitter:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext




